### PR TITLE
add support section

### PR DESCRIPTION
**Pull request by mattbennett**

### CODE REVIEW

**Comment by kylesome** [comment]
interesting service, are they a sponsor now or something?

**Comment by mattbennett** [comment]
Man I could have used your help with this yesterday! Was banging my head against Gatsby all day 😆 

They're not a sponsor per se, but Nameko is covered by their subscription, which means you get certain assurances like compatible licences, security notifications, deprecation warnings and so on. Really neat idea.

**Comment by davidszotten** [comment]
the banner is pretty large on mobile, are there smaller versions we could switch in? or maybe just give it some more breathing room / move it down?

**Comment by kylesome** [comment]
> Man I could have used your help with this yesterday! Was banging my head against Gatsby all day 😆

Hehe, yeah it can be tricky sometimes, especially with css, feel free to pop me an email if you have any other questions about it :)

> the banner is pretty large on mobile, are there smaller versions we could switch in? or maybe just
> give it some more breathing room / move it down?

I'd be happy to see if Andreea has any opinions about it, there are a few examples in other components where there are different styles for mobile, just wrap it in

```js
${media.mobile`
  // some mobile styles
`};
```

**Comment by mattbennett** [comment]
@davidszotten I agree it is a bit dominant on mobile. It's not a pre-built widget so we're only limited by design skills (i.e. quite limited if I do it!).

@kylesome if Andreea has any suggestions I would be grateful! Thanks!

**Comment by renieness** [comment]
@mattbennett Hello! Maybe you could do a horizontal banner across the top of the page? That would work nicely on mobile and desktop. But if you think that it shouldn't be the first element on the page, maybe a secondary call to action next to the 'Get Started' button.

I would also recommend not using all caps for that text, as it reduces legibility. And I know you're probably using the orange from Tidelift, but I don't think it stands out enough against the purple. You could try the Nameko orange #fa7f13

Hope that helps and also feel free to shoot me an email - my email address is hrincu@gmail.com

**Pull request merged**
